# Generated by Django 6.0 on 2025-12-12 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merk', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('tahun', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('plat_nomor', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Format plat nomor tidak valid (contoh: B 1234 ABC)', regex='^[A-Z]{1,2}\\s?\\d{1,4}\\s?[A-Z]{1,3}$')])),
                ('harga_sewa_per_hari', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('tersedia', 'Tersedia'), ('disewa', 'Disewa'), ('perbaikan', 'Perbaikan')], default='tersedia', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mobil',
                'verbose_name_plural': 'Daftar Mobil',
                'db_table': 'mobil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='NIK harus 16 digit angka', regex='^\\d{16}$')])),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField(blank=True, default='')),
                ('no_telepon', models.CharField(blank=True, default='', max_length=15)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pelanggan',
                'verbose_name_plural': 'Daftar Pelanggan',
                'db_table': 'pelanggan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=15)),
                ('metode_pembayaran', models.CharField(choices=[('tunai', 'Tunai'), ('transfer', 'Transfer Bank'), ('kartu_kredit', 'Kartu Kredit')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('lunas', 'Lunas'), ('gagal', 'Gagal')], default='pending', max_length=20)),
                ('bukti_pembayaran', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pembayaran',
                'verbose_name_plural': 'Daftar Pembayaran',
                'db_table': 'pembayaran',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Penyewaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_penyewaan', models.CharField(blank=True, max_length=20, unique=True)),
                ('tanggal_sewa', models.DateField()),
                ('tanggal_kembali', models.DateField()),
                ('tanggal_pengembalian', models.DateField(blank=True, null=True)),
                ('total_hari', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_biaya', models.DecimalField(decimal_places=2, max_digits=15)),
                ('denda', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('selesai', 'Selesai'), ('terlambat', 'Terlambat')], default='aktif', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Penyewaan',
                'verbose_name_plural': 'Daftar Penyewaan',
                'db_table': 'penyewaan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogAktivitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, default='system', max_length=100)),
                ('aksi', models.CharField(choices=[('create', 'Tambah'), ('update', 'Ubah'), ('delete', 'Hapus'), ('view', 'Lihat'), ('login', 'Login'), ('logout', 'Logout')], max_length=20)),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, default='', max_length=255)),
                ('perubahan', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log Aktivitas',
                'verbose_name_plural': 'Log Aktivitas',
                'db_table': 'log_aktivitas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('pesan', models.TextField()),
                ('tipe', models.CharField(choices=[('info', 'Informasi'), ('warning', 'Peringatan'), ('success', 'Sukses'), ('error', 'Error')], default='info', max_length=20)),
                ('kategori', models.CharField(choices=[('penyewaan_baru', 'Penyewaan Baru'), ('pembayaran', 'Pembayaran'), ('pengembalian', 'Pengembalian'), ('keterlambatan', 'Keterlambatan'), ('reminder', 'Pengingat'), ('sistem', 'Sistem')], default='sistem', max_length=30)),
                ('penyewaan_id_ref', models.IntegerField(blank=True, null=True, verbose_name='ID Penyewaan')),
                ('pelanggan_id_ref', models.IntegerField(blank=True, null=True, verbose_name='ID Pelanggan')),
                ('pelanggan_nama', models.CharField(blank=True, default='', max_length=100, verbose_name='Nama Pelanggan')),
                ('dibaca', models.BooleanField(default=False)),
                ('dikirim_email', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notifikasi',
                'verbose_name_plural': 'Daftar Notifikasi',
                'db_table': 'notifikasi',
                'ordering': ['-created_at'],
            },
        ),
    ]
