# Generated by Django 5.2.9 on 2025-12-17 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.IntegerField(db_index=True)),
                ('version', models.IntegerField(default=1)),
                ('data_snapshot', models.JSONField(help_text='Snapshot lengkap data object dalam JSON')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('commit', 'Commit'), ('rollback', 'Rollback')], default='commit', max_length=20)),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commit_message', models.TextField(blank=True, default='', help_text='Pesan commit untuk menjelaskan perubahan')),
                ('branch', models.CharField(default='main', help_text='Nama branch', max_length=50)),
                ('is_current', models.BooleanField(default=True, help_text='Apakah ini versi aktif saat ini')),
                ('parent_version', models.ForeignKey(blank=True, help_text='Versi sebelumnya (parent)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='rental.dataversion')),
            ],
            options={
                'verbose_name': 'Data Version',
                'verbose_name_plural': 'Data Versions',
                'db_table': 'data_version',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='data_versio_model_n_23edc7_idx'), models.Index(fields=['branch'], name='data_versio_branch_f25df2_idx')],
                'unique_together': {('model_name', 'object_id', 'version', 'branch')},
            },
        ),
    ]
